---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  namespace: flux-system
  name: web-platform
spec:
  image: ghcr.io/poc-gitops/web-platform/web-platform
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  namespace: flux-system
  name: web-platform
spec:
  imageRepositoryRef:
    name: web-platform
  filterTags:
    pattern: '^m-[a-fA-F0-9]+-(?P<datetime>.*)'
    extract: '$datetime'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  namespace: flux-system
  name: web-platform
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: web-platform
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: k8s/dev
    strategy: Setters
