replicaCount: 2

image:
  repository: nginx

containerPort: 8080

ingress:
  enabled: true
  className: "cloduflare-tunnel"
  hosts:
    - host: web-platform-prod.mhcp001.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
